version: '3.8'

services:
  bot:
    build: .
    container_name: tradingview-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    ports:
      - "3000:3000"   # Eğer web server varsa, gerekirse
